name:         rewire
version:      2.6
synopsis:     A Haskell-to-Verilog compiler
description:  A compiler for a subset of Haskell to Verilog and VHDL.
homepage:     https://github.com/mu-chaco/ReWire
license:      BSD3
license-file: LICENSE
category:     Language
build-type:   Simple
github:       twosixlabs/ReWire.git
maintainer:   Chris Hathhorn <hathhorn@gmail.com>
author:
- Adam Procter
- Chris Hathhorn <hathhorn@gmail.com>
- Ian Graves
- William L. Harrison
- Matthew Heimerdinger

ghc-options:
- -Wall
- -fno-warn-name-shadowing
- -funbox-strict-fields
- -O2
- -optc-O3
- -j8 +RTS -A64m -RTS
default-extensions:
- LambdaCase
- TupleSections
- ViewPatterns

extra-source-files:
- README.md
data-files:
- tests/integration/*.hs
- tests/regression/Mods/*.hs
- tests/regression/OD19/*.hs
- tests/regression/Mods/C/*.hs
- tests/regression/verilog/*.sv
- tests/regression/*.hs
- tests/regression/*.sv
- tests/regression/*.rwc
- tests/regression/*.yaml
- rewire-user/src/*.hs
- rewire-user/src/RWC/*.hs
- rewire-user/src/ReWire/*.hs
- tutorial/SHA256/*.hs
- tutorial/*/*
- tutorial/*/*/*
- tutorial/*/*/*/*

dependencies:
- base ^>= 4.20
- ghc ^>= 9.10
- directory ^>= 1.3
- filepath ^>= 1.5
- lens ^>= 5.3
- rewire-user ^>= 0.2
- text ^>= 2.1
- rewire-embedder

library:
  source-dirs: src
  dependencies:
  - rewire-core

executables:
  rwc:
    source-dirs: apps/rwc
    main: Main.hs
    dependencies:
    - rewire

  rwe:
    source-dirs: apps/rwe
    main: Main.hs
    dependencies:
    - rewire

  firrtl:
    source-dirs: apps/firrtl
    main: Main.hs
    dependencies:
    - rewire-core

tests:
  rwc-test:
    source-dirs: apps/rwc-test
    main: Main.hs
    dependencies:
    - rewire
    - HUnit ^>= 1.6
    - directory ^>= 1.3
    - process ^>= 1.6
    - filepath ^>= 1.5
    - tasty ^>= 1.5
    - tasty-hunit ^>= 0.10
    - tasty-golden ^>= 2.3

  rwe-test:
    source-dirs: apps/rwe-test
    main: Main.hs
    dependencies:
    - rewire
    - HUnit ^>= 1.6
    - directory ^>= 1.3
    - process ^>= 1.6
    - filepath ^>= 1.5
    - tasty ^>= 1.5
    - tasty-hunit ^>= 0.10
