name:         rewire-embedder
version:      2.5.1
synopsis:     A ReWire-to-Isabelle embedder
description:  For verification using the ReWire hardware description language
homepage:     https://github.com/mu-chaco/ReWire
license:      NONE
license-file: LICENSE
category:     Language
build-type:   Simple
github:       twosixlabs/ReWire.git
maintainer:
- Matthew Heimerdinger <matthew.heimerdinger@gmail.com>
- Chris Hathhorn <hathhorn@gmail.com>
author:
- Adam Procter
- Chris Hathhorn <hathhorn@gmail.com>
- Ian Graves
- William L. Harrison
- Matthew Heimerdinger

ghc-options:
- -Wall
- -fno-warn-name-shadowing
- -funbox-strict-fields
- -O2
- -optc-O3
- -j8 +RTS -A64m -RTS
default-extensions:
- LambdaCase
- TupleSections
- ViewPatterns

extra-source-files:
- README.md

dependencies:
- rewire-user >= 0.1
- base ^>= 4.18
- bv ^>= 0.5
- containers ^>= 0.6
- deepseq ^>= 1.4
- directory ^>= 1.3
- exceptions ^>= 0.10
- filepath ^>= 1.4
- ghc ^>= 9.6
- ghc-boot ^>= 9.6
- hashable ^>= 1.4
- haskell-src-exts ^>= 1.23
- lens ^>= 5.2
- machines ^>= 0.7
- megaparsec ^>= 9.5
- mtl ^>= 2.3
- prettyprinter ^>= 1.7
- split ^>= 0.2
- text ^>= 2.0
- text-show ^>= 3.10
- unbound-generics ^>= 0.4
- unordered-containers ^>= 0.2
- yaml ^>= 0.11

library:
  source-dirs: src
