name:         rewire-user
version:      0.1.0.0
description:  Please see the README.
github:       "githubuser/rewire-user"
license:      NONE
license-file: LICENSE
maintainer:   Chris Hathhorn <hathhorn@gmail.com>
author:
- Matthew Heimerdinger
- Chris Hathhorn

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- mtl
- monad-resumption
- vector-sized
- finite-typelits
- ghc-typelits-natnormalise

library:
  source-dirs: src

tests:
  rewire-user-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rewire-user
